[package]
name = "personal-portfolio-website-builder"
version = "0.0.1"
authors = ["Shivanand Pattanshetti <shiva.patt.work@gmail.com>"]
edition = "2021"

[features]
default = []
web = ["dioxus-web", "dioxus-router/web"]
ssr = [    
    "dioxus-ssr",
    "dioxus-router/ssr",
    "tokio",
    "dioxus-fullstack/axum",
    "axum",
]
prebuild = ["ssr"]

[dependencies]
dioxus = { version = "0.4" }
dioxus-web = { version = "0.4", features = ["hydrate"], optional = true }
dioxus-ssr = { version = "0.4", optional = true }
dioxus-fullstack = { version = "0.4", features = ["router",] }
dioxus-router = { version = "0.4" }
tokio = { version = "1.29", features = ["full"], optional = true }
axum = { version = "0.6", optional = true }
